### PR TITLE
Issue #7: Add Navigation Links

### PR DESCRIPTION
**Pull request by ahmedmeshref**
## Add Navigation Links

I have added navigation links in the navbar to navigate to the different sections [ projects, experience, education] of the page. The navigation links are useful to navigate easily to different sections of the page especially when the portfolio gets larger.

### CODE REVIEW

**Review by ahmedmeshref — COMMENTED** [review]
Fix scss file

**Comment by ayushmaang** [comment]
Could you do me a favor and add a screenshot of the before and after of your work?

**Comment by ahmedmeshref** [comment]
@ayushmaang you can visit the deployed version of this branch on https://deploy-preview-3--mlh-template.netlify.app/
Basically, I have added navigation links at the top of the page under the MLH logo to navigate to different sections of the page.

**Comment by ayushmaang** [comment]
The websites look solid. I'd love to see you both customize the repo now so it's actually your own portfolio.

**Pull request merged**
