### PR TITLE
Issue #6: Bio section

### PR DESCRIPTION
**Pull request by jordanhilado**
Added a section under the title/name that can be adjusted in the config YAML file. This makes it easier for the user to edit their bio alongside their other profile configurations.

### CODE REVIEW

**Comment by ayushmaang** [comment]
Fix the merge conflicts.

**Comment by ayushmaang** [comment]
Looks solid.

**Comment by ayushmaang** [comment]
Fix the merge conflict though.

**Comment by jordanhilado** [comment]
Fixed 👍

**Comment by ayushmaang** [comment]
Looks good now.

**Pull request merged**
